export type Area = {
  slug: string;
  name: string;
  county: string;
  zip: string[];
  population: string;
  lat: number;
  lng: number;
  intro: string; // unique, AI-extractable definition-style intro
  why: string;   // why dryer vent cleaning matters specifically here
  neighborhoods: string[];
  landmarks: string[];
  drivers: string[]; // SEO-relevant local context
  placeholder?: boolean; // Tier 2 stub — noindex until Phase 4 content build
};

export const areas: Area[] = [
  {
    slug: 'tampa',
    name: 'Tampa',
    county: 'Hillsborough',
    zip: ['33602', '33603', '33604', '33605', '33606', '33607', '33609', '33610', '33611', '33612', '33613', '33614', '33615', '33616', '33617', '33618', '33619', '33620', '33621', '33624', '33625', '33626', '33629', '33634', '33635', '33637'],
    population: '403,000+',
    lat: 27.9506,
    lng: -82.4572,
    intro: 'Dryer vent cleaning in Tampa is essential because the city\'s combination of high humidity, year-round dryer use, and aging housing stock creates ideal conditions for dangerous lint accumulation. Tampa homes typically need professional vent cleaning every 12 months — more frequently for households with pets or large families.',
    why: 'Tampa\'s subtropical climate produces some of the highest dew points in the continental U.S. between May and October. This humidity combines with constant air conditioning use and frequent dryer cycles to create thick, compacted lint that ordinary cleaning cannot remove. Many Tampa homes built before 2005 also have long, multi-bend vent runs that trap lint at every joint.',
    neighborhoods: ['Hyde Park', 'SoHo', 'Davis Islands', 'Seminole Heights', 'Ybor City', 'Channelside', 'Westshore', 'Carrollwood', 'New Tampa', 'Westchase'],
    landmarks: ['Tampa International Airport', 'University of South Florida', 'Tampa General Hospital', 'Raymond James Stadium', 'Amalie Arena'],
    drivers: ['high humidity year-round', 'large condo and townhome inventory', 'rapid population growth driving rental market', 'older homes in established neighborhoods'],
  },
  {
    slug: 'st-petersburg',
    name: 'St. Petersburg',
    county: 'Pinellas',
    zip: ['33701', '33702', '33703', '33704', '33705', '33706', '33707', '33708', '33709', '33710', '33711', '33712', '33713', '33714', '33715', '33716'],
    population: '258,000+',
    lat: 27.7676,
    lng: -82.6403,
    intro: 'Dryer vent cleaning in St. Petersburg is critical due to the city\'s coastal salt air, dense concentration of mid-century homes, and high percentage of multi-family buildings where shared vent infrastructure compounds fire risk. St. Pete homeowners should schedule professional cleanings annually at minimum.',
    why: 'St. Petersburg\'s peninsular geography means salt-laden coastal air corrodes metal vent components faster than inland areas. Combined with the city\'s many condos and 55+ communities — where dryers run multiple times per day — vent systems here accumulate lint and degrade twice as fast as the national average.',
    neighborhoods: ['Old Northeast', 'Downtown', 'Snell Isle', 'Shore Acres', 'Tyrone', 'Crescent Lake', 'Kenwood', 'Disston Heights', 'Greater Pinellas Point'],
    landmarks: ['Tropicana Field', 'St. Pete Pier', 'Salvador Dalí Museum', 'Sunken Gardens', 'Vinoy Park'],
    drivers: ['coastal salt corrosion', 'high condo and 55+ community density', 'older mid-century housing', 'tourist rental units with heavy laundry use'],
  },
  {
    slug: 'clearwater',
    name: 'Clearwater',
    county: 'Pinellas',
    zip: ['33755', '33756', '33759', '33760', '33761', '33762', '33763', '33764', '33765', '33767'],
    population: '117,000+',
    lat: 27.9659,
    lng: -82.8001,
    intro: 'Clearwater dryer vent cleaning addresses unique challenges from the city\'s beachside humidity, large vacation rental market, and mix of high-rise condos and single-family homes. Vacation rentals in particular need quarterly professional cleaning due to back-to-back guest laundry loads.',
    why: 'Clearwater Beach properties experience some of the highest dryer usage rates in Florida due to constant tourist turnover. Sand and salt enter vent systems through outdoor airflow, mixing with lint to form an abrasive coating that damages dryer components and accelerates fire risk.',
    neighborhoods: ['Clearwater Beach', 'Sand Key', 'Island Estates', 'Countryside', 'East Lake', 'Morningside', 'Skycrest'],
    landmarks: ['Clearwater Beach', 'Pier 60', 'Clearwater Marine Aquarium', 'Coachman Park'],
    drivers: ['vacation rental turnover', 'beachside salt and sand exposure', 'high-rise condo concentration', 'snowbird seasonal occupancy'],
  },
  {
    slug: 'brandon',
    name: 'Brandon',
    county: 'Hillsborough',
    zip: ['33508', '33509', '33510', '33511'],
    population: '114,000+',
    lat: 27.9378,
    lng: -82.2859,
    intro: 'Brandon dryer vent cleaning is especially important for the area\'s many family-sized homes and growing suburban developments where high-volume laundry use accelerates lint buildup. Most Brandon homes benefit from annual professional cleaning to maintain dryer efficiency and prevent fire hazards.',
    why: 'Brandon\'s rapid suburban expansion means many homes have longer-than-average vent runs to meet code in newer subdivisions. These extended runs — often 25+ feet with multiple 90-degree bends — accumulate lint at nearly twice the rate of standard installations and require specialized cleaning equipment.',
    neighborhoods: ['Bloomingdale', 'Brandon Lakes', 'FishHawk Ranch', 'Heather Lakes', 'Providence Lakes'],
    landmarks: ['Westfield Brandon Mall', 'Brandon Regional Hospital', 'Bloomingdale Golfers Club'],
    drivers: ['large family homes', 'long vent runs in newer construction', 'master-planned community density', 'year-round high humidity'],
  },
  {
    slug: 'riverview',
    name: 'Riverview',
    county: 'Hillsborough',
    zip: ['33569', '33578', '33579'],
    population: '108,000+',
    lat: 27.8661,
    lng: -82.3265,
    intro: 'Riverview dryer vent cleaning serves one of Tampa Bay\'s fastest-growing communities, where new construction and high turnover from young families create heavy demand for residential vent maintenance. Annual cleaning is the minimum recommended frequency for most Riverview households.',
    why: 'Riverview\'s explosive growth has produced thousands of homes built within the last 15 years. While newer than older Tampa stock, these homes are typically larger with multiple stories — meaning vent runs travel through walls and ceilings where blockages are difficult to detect without professional inspection.',
    neighborhoods: ['Panther Trace', 'Summerfield', 'South Pointe', 'Boyette Springs', 'Rivercrest'],
    landmarks: ['Alafia River', 'St. Joseph\'s Hospital-South', 'Riverview High School'],
    drivers: ['rapid new construction', 'large two-story homes', 'young family demographics', 'multi-story vent routing'],
  },
  {
    slug: 'wesley-chapel',
    name: 'Wesley Chapel',
    county: 'Pasco',
    zip: ['33543', '33544', '33545'],
    population: '64,000+',
    lat: 28.2392,
    lng: -82.3279,
    intro: 'Wesley Chapel dryer vent cleaning supports a community of master-planned developments where uniform construction means widespread, predictable vent issues — making proactive professional cleaning especially valuable for preventing fire hazards before they develop.',
    why: 'Wesley Chapel communities like Seven Oaks, Meadow Pointe, and Wiregrass Ranch were built rapidly using similar floor plans. This means homes in the same neighborhood often share identical vent routing flaws — and identical timelines for when lint blockages become dangerous.',
    neighborhoods: ['Seven Oaks', 'Meadow Pointe', 'Wiregrass Ranch', 'Bridgewater', 'Watergrass', 'Estancia'],
    landmarks: ['Tampa Premium Outlets', 'The Shops at Wiregrass', 'AdventHealth Wesley Chapel'],
    drivers: ['master-planned uniformity', 'rapid suburban growth', 'large single-family homes', 'family-heavy demographics'],
  },
  {
    slug: 'new-tampa',
    name: 'New Tampa',
    county: 'Hillsborough',
    zip: ['33647'],
    population: '50,000+',
    lat: 28.1144,
    lng: -82.3483,
    intro: 'New Tampa dryer vent cleaning addresses the unique needs of this upscale planned community where larger homes, premium appliances, and longer vent routing combine to require more thorough professional cleaning than standard residential properties.',
    why: 'New Tampa\'s gated communities like Tampa Palms, Cory Lake Isles, and Hunters Green feature executive homes with vent runs frequently exceeding 30 feet. Premium dryers in these homes operate at higher heat and longer cycles, accelerating lint accumulation despite owner expectations of newer equipment requiring less maintenance.',
    neighborhoods: ['Tampa Palms', 'Cory Lake Isles', 'Hunters Green', 'West Meadows', 'Cross Creek'],
    landmarks: ['Flatwoods Park', 'Tampa Palms Golf & Country Club', 'University of South Florida campus border'],
    drivers: ['executive-size homes', 'extra-long vent runs', 'premium dryer equipment', 'gated community standards'],
  },
  {
    slug: 'carrollwood',
    name: 'Carrollwood',
    county: 'Hillsborough',
    zip: ['33618', '33624'],
    population: '40,000+',
    lat: 28.0506,
    lng: -82.5019,
    intro: 'Carrollwood dryer vent cleaning is especially important for the area\'s established mid-century homes, many of which still have original vent ducting that has accumulated decades of lint and may not meet current safety codes.',
    why: 'Carrollwood was developed primarily in the 1960s and 70s, meaning many original homes have aging vent infrastructure — often flexible plastic or foil ducting that is now considered a fire hazard and banned by code. Professional cleaning frequently uncovers urgent replacement needs.',
    neighborhoods: ['Original Carrollwood', 'Carrollwood Village', 'Lake Carroll', 'Northdale'],
    landmarks: ['Lake Carroll', 'Carrollwood Cultural Center', 'St. Joseph\'s Hospital-North'],
    drivers: ['mid-century housing stock', 'outdated vent materials', 'mature established neighborhoods', 'long-term homeowners'],
  },
  {
    slug: 'westchase',
    name: 'Westchase',
    county: 'Hillsborough',
    zip: ['33626'],
    population: '23,000+',
    lat: 28.0586,
    lng: -82.6175,
    intro: 'Westchase dryer vent cleaning serves an upscale planned community where consistent home design across the neighborhood means similar vent maintenance schedules and predictable issues. Annual cleaning is the standard recommendation for Westchase residents.',
    why: 'Westchase was built in the late 1990s and early 2000s with predominantly two-story floor plans where dryers are located on the second floor. This routing requires vents to travel down through wall cavities — a configuration prone to gravity-fed lint accumulation in lower wall sections.',
    neighborhoods: ['Greens of Westchase', 'Bennington', 'Stockbridge', 'Castleford', 'Berkeley Village'],
    landmarks: ['Westchase Golf Club', 'Westchase Town Center', 'Citrus Park Town Center nearby'],
    drivers: ['second-floor laundry rooms', 'consistent housing age', 'family demographic', 'uniform vent routing'],
  },
  {
    slug: 'south-tampa',
    name: 'South Tampa',
    county: 'Hillsborough',
    zip: ['33606', '33611', '33616', '33629'],
    population: '90,000+',
    lat: 27.8881,
    lng: -82.4823,
    intro: 'South Tampa dryer vent cleaning serves the city\'s most affluent and oldest neighborhoods, where historic homes from the 1920s through 1960s often have unique vent challenges including original brick exterior penetrations, narrow utility chases, and incompatible modern dryer installations.',
    why: 'South Tampa neighborhoods like Hyde Park, Davis Islands, and Bayshore include many homes over 60 years old with vent systems that were retrofitted multiple times. These homes commonly have undersized vent diameters, improper materials, and routing that doesn\'t meet current safety code — making professional inspection critical.',
    neighborhoods: ['Hyde Park', 'Davis Islands', 'Bayshore Beautiful', 'Palma Ceia', 'SoHo', 'Beach Park', 'Sunset Park'],
    landmarks: ['Bayshore Boulevard', 'Hyde Park Village', 'MacDill Air Force Base', 'University of Tampa'],
    drivers: ['historic housing stock', 'high-end home values', 'retrofitted vent systems', 'narrow utility spaces'],
  },
  {
    slug: 'lutz',
    name: 'Lutz',
    county: 'Hillsborough',
    zip: ['33548', '33549', '33558'],
    population: '24,000+',
    lat: 28.1511,
    lng: -82.4617,
    intro: 'Lutz dryer vent cleaning serves a mix of suburban developments and rural properties where larger lot sizes often mean longer vent routing through detached laundry rooms, garages, or pool houses — configurations that require specialized cleaning approaches.',
    why: 'Lutz\'s combination of established suburban subdivisions and equestrian-zoned properties produces unusually varied vent installations. Pool houses, detached garages, and converted barns often contain laundry equipment with non-standard venting that conventional cleaning services cannot properly address.',
    neighborhoods: ['Cheval', 'Heritage Harbor', 'Stonebrier', 'Calusa Trace', 'Lake Park'],
    landmarks: ['Lake Park', 'Cheval Golf & Country Club', 'Lutz Community Center'],
    drivers: ['large lot rural properties', 'detached structures with laundry', 'mixed suburban and equestrian zoning', 'non-standard installations'],
  },
  {
    slug: 'land-o-lakes',
    name: 'Land O\' Lakes',
    county: 'Pasco',
    zip: ['34637', '34638', '34639'],
    population: '37,000+',
    lat: 28.2189,
    lng: -82.4595,
    intro: 'Land O\' Lakes dryer vent cleaning supports a community where rapid suburban growth has created neighborhoods of newer two-story homes with complex vent routing — increasing both the importance of professional cleaning and the difficulty of doing it correctly.',
    why: 'Land O\' Lakes communities like Connerton, Stagecoach, and Lake Padgett feature homes built in the last 20 years where dryers are commonly located in second-floor laundry rooms with vents traveling 20-40 feet through interior walls before exiting. These extended runs require professional rotary brush systems for proper cleaning.',
    neighborhoods: ['Connerton', 'Stagecoach', 'Lake Padgett Estates', 'Sundance', 'Wilderness Lake'],
    landmarks: ['Lake Padgett', 'Connerton Preserve', 'Florida Hospital Wesley Chapel nearby'],
    drivers: ['second-floor laundry standard', 'long interior wall vent runs', 'rapid suburban growth', 'family-sized homes'],
  },
  {
    slug: 'plant-city',
    name: 'Plant City',
    county: 'Hillsborough',
    zip: ['33563', '33565', '33566', '33567'],
    population: '40,000+',
    lat: 28.0188,
    lng: -82.1148,
    intro: 'Plant City dryer vent cleaning serves a community where agricultural surroundings introduce unique contamination sources — pollen, crop dust, and field debris can enter dryer vent systems and combine with lint to create unusually dense, fire-prone blockages.',
    why: 'Plant City\'s position in the heart of Florida\'s strawberry country means homes here deal with seasonal agricultural particulate that infiltrates vent systems through outdoor terminations. This adds a layer of pollen and crop dust to standard lint accumulation, requiring more frequent professional cleaning — typically every 6-9 months.',
    neighborhoods: ['Walden Lake', 'Strawberry Ridge', 'North Park Isle', 'Country Hills'],
    landmarks: ['Florida Strawberry Festival grounds', 'Plant City High School', 'McCall Park'],
    drivers: ['agricultural particulate exposure', 'seasonal pollen infiltration', 'mixed rural-suburban housing', 'older established homes'],
  },
  {
    slug: 'apollo-beach',
    name: 'Apollo Beach',
    county: 'Hillsborough',
    zip: ['33572'],
    population: '24,000+',
    lat: 27.7714,
    lng: -82.4035,
    intro: 'Apollo Beach dryer vent cleaning addresses the specific risks of waterfront living, where salt-laden air, high humidity, and the popularity of premium homes with multiple laundry rooms create an environment requiring vigilant vent maintenance.',
    why: 'Apollo Beach\'s extensive canal system places nearly every home within yards of saltwater. Salt aerosol enters dryer vents through outdoor terminations and accelerates corrosion of metal ducting, dryer heating elements, and exterior vent hoods. Many homes here also have dual laundry setups that double both the risk and the cleaning frequency needed.',
    neighborhoods: ['MiraBay', 'Symphony Isles', 'Andalucia', 'Waterset', 'Apollo Beach Estates'],
    landmarks: ['Apollo Beach Nature Preserve', 'TECO Manatee Viewing Center', 'Apollo Beach Marina'],
    drivers: ['waterfront salt exposure', 'premium homes with dual laundry', 'high humidity year-round', 'aging metal vent components'],
  },
  {
    slug: 'valrico',
    name: 'Valrico',
    county: 'Hillsborough',
    zip: ['33594', '33596'],
    population: '37,000+',
    lat: 27.9389,
    lng: -82.2370,
    intro: 'Valrico dryer vent cleaning serves an established suburban community east of Tampa where mid-2000s construction has reached the age where original vent installations need professional inspection and cleaning to prevent fire hazards from accumulated lint.',
    why: 'Valrico communities like FishHawk Ranch, Bloomingdale, and River Hills were largely developed in the late 1990s through mid-2000s. Homes here are now 20+ years old — well past the point where original vent components and any flexible ducting installed at construction are considered safe by current standards.',
    neighborhoods: ['FishHawk Ranch', 'Bloomingdale', 'River Hills', 'Diamond Hill', 'Buckhorn'],
    landmarks: ['FishHawk Sports Complex', 'Bloomingdale Golfers Club', 'Brandon Regional Hospital nearby'],
    drivers: ['aging mid-2000s construction', 'large family homes', 'master-planned community density', 'original vent components reaching end of life'],
  },
  {
    slug: 'sun-city-center',
    name: 'Sun City Center',
    county: 'Hillsborough',
    zip: ['33573', '33574'],
    population: '27,000+',
    lat: 27.7153,
    lng: -82.3525,
    intro: 'Sun City Center dryer vent cleaning is essential for this large 55+ active-adult community, where high daily dryer usage across Kings Point and surrounding neighborhoods makes professional annual cleaning a core fire-safety task for residents and HOA boards alike.',
    why: 'Sun City Center residents tend to run dryers frequently in smaller loads — a usage pattern that accumulates lint faster than standard households. Many original Kings Point villas and detached homes date to the 1960s–80s and have vent systems that have never been professionally inspected.',
    neighborhoods: ['Kings Point', 'Renaissance', 'Del Webb Sun City Center', 'Cypress Creek'],
    landmarks: ['Kings Point Clubhouse', 'South Bay Hospital', 'Sun City Center Plaza'],
    drivers: ['55+ retirement community density', 'heavy daily dryer use', 'aging original vent infrastructure', 'HOA and property management contracts'],
    placeholder: true,
  },
  {
    slug: 'dunedin',
    name: 'Dunedin',
    county: 'Pinellas',
    zip: ['34698'],
    population: '36,000+',
    lat: 28.0199,
    lng: -82.7723,
    intro: 'Dunedin dryer vent cleaning protects homes in this coastal Pinellas town where Gulf salt air, 1950s bungalow housing stock, and a strong shop-local culture make locally-owned professional vent service a natural fit for residents.',
    why: 'Dunedin\'s waterfront location exposes homes to constant salt aerosol that corrodes metal vent components. Many original bungalows still have undersized or outdated vent materials that current code would reject, creating both a fire risk and a repair opportunity during annual cleaning.',
    neighborhoods: ['Downtown Dunedin', 'Honeymoon Island area', 'Edgewater', 'Fairway Estates'],
    landmarks: ['Honeymoon Island State Park', 'Pinellas Trail', 'Dunedin Stadium'],
    drivers: ['coastal salt air corrosion', '1950s bungalow housing stock', 'shop-local community culture', 'Gulf-front humidity'],
    placeholder: true,
  },
  {
    slug: 'largo',
    name: 'Largo',
    county: 'Pinellas',
    zip: ['33770', '33771', '33773', '33774', '33778'],
    population: '84,000+',
    lat: 27.9094,
    lng: -82.7873,
    intro: 'Largo dryer vent cleaning serves a dense mid-Pinellas community that mixes single-family homes, condos, and a significant mobile home population — each housing type bringing its own vent-system challenges that benefit from a locally-owned professional service.',
    why: 'Largo\'s wide mix of housing — from 1960s ranches to modern condos to mobile home parks — means vent systems here vary dramatically in age, material, and code compliance. Generic national franchises often skip mobile home work; a local team handles the full range.',
    neighborhoods: ['Belleair Bluffs', 'Indian Rocks Beach corridor', 'Harbor Bluffs', 'East Bay'],
    landmarks: ['Largo Central Park', 'Pinellas County Heritage Village', 'Largo Medical Center'],
    drivers: ['dense mixed housing stock', 'mobile home park concentration', 'mid-century ranch homes', 'mid-Pinellas central location'],
    placeholder: true,
  },
  {
    slug: 'pinellas-park',
    name: 'Pinellas Park',
    county: 'Pinellas',
    zip: ['33781', '33782'],
    population: '53,000+',
    lat: 27.8428,
    lng: -82.6995,
    intro: 'Pinellas Park dryer vent cleaning addresses the needs of this working- and middle-class community where aging mid-century homes, dense residential stock, and a substantial mobile home presence create consistent demand for affordable, thorough vent service.',
    why: 'Pinellas Park has one of the highest concentrations of homes built before 1980 in the region, with corresponding vent systems that are frequently undersized, kinked, or running on outdated flexible ducting. A single cleaning visit often uncovers multiple code issues worth addressing.',
    neighborhoods: ['Mainlands', 'Cross Bayou', 'Central Park', 'Hainan'],
    landmarks: ['Freedom Lake Park', 'Pinellas Park Performing Arts Center', 'Helen Howarth Park'],
    drivers: ['dense pre-1980 housing', 'mobile home park concentration', 'working-class affordability focus', 'aging vent infrastructure'],
    placeholder: true,
  },
  {
    slug: 'new-port-richey',
    name: 'New Port Richey',
    county: 'Pasco',
    zip: ['34652', '34653', '34654', '34655'],
    population: '17,000+',
    lat: 28.2441,
    lng: -82.7192,
    intro: 'New Port Richey dryer vent cleaning supports a Gulf-adjacent community where salt air, canal-front homes, and a large retirement population combine to require more frequent professional vent maintenance than inland Tampa Bay.',
    why: 'Many New Port Richey homes sit directly on or near the Gulf Harbors canal system, exposing exterior vent hoods to continuous salt aerosol. Combined with year-round dryer use by retirees, this accelerates component corrosion and lint compaction beyond average Tampa Bay rates.',
    neighborhoods: ['Gulf Harbors', 'Seven Springs', 'River Ridge', 'Downtown New Port Richey', 'Jasmine Estates'],
    landmarks: ['Sims Park', 'Gulf Harbors Beach Club', 'Starkey Wilderness Preserve'],
    drivers: ['Gulf-front salt air', 'retirement community density', 'canal-adjacent corrosion', 'year-round heavy dryer use'],
    placeholder: true,
  },
  {
    slug: 'odessa',
    name: 'Odessa',
    county: 'Pasco',
    zip: ['33556'],
    population: '11,000+',
    lat: 28.1844,
    lng: -82.5906,
    intro: 'Odessa dryer vent cleaning serves an affluent horse-country and master-planned area on the Hillsborough-Pasco border, where larger-than-average home footprints and long vent runs make professional cleaning a standard part of home maintenance.',
    why: 'Odessa includes Starkey Ranch and surrounding master-planned neighborhoods with executive-scale homes that routinely have vent runs exceeding 30 feet through multi-story floor plans. These long runs collect lint at every bend and require commercial rotary brush equipment for thorough cleaning.',
    neighborhoods: ['Starkey Ranch', 'Keystone', 'Ivy Lake Estates', 'Longleaf'],
    landmarks: ['Starkey Wilderness Park', 'Lake Keystone', 'Starkey Ranch District Park'],
    drivers: ['affluent master-planned homes', 'long vent runs in executive homes', 'equestrian-zoned large lots', 'mixed Hillsborough-Pasco geography'],
    placeholder: true,
  },
  {
    slug: 'bradenton',
    name: 'Bradenton',
    county: 'Manatee',
    zip: ['34201', '34202', '34203', '34205', '34207', '34208', '34209', '34210', '34211', '34212'],
    population: '56,000+',
    lat: 27.4989,
    lng: -82.5748,
    intro: 'Bradenton dryer vent cleaning reaches the fast-growing Manatee County market, anchored by Lakewood Ranch — one of the largest master-planned communities in the United States. At roughly 45 miles from Tampa, Bradenton sits within our 50-mile Tampa-based service radius.',
    why: 'Lakewood Ranch alone encompasses more than 20,000 homes, many built in the last 15 years with vent runs that are now hitting their first deep-clean need. Combined with older downtown Bradenton and west-Bradenton coastal homes, the county represents a mix of modern and legacy vent systems a single local team can handle.',
    neighborhoods: ['Lakewood Ranch', 'West Bradenton', 'Palma Sola', 'Cortez', 'Bayshore Gardens'],
    landmarks: ['LECOM Park', 'South Florida Museum', 'Lakewood Ranch Main Street'],
    drivers: ['Lakewood Ranch master-planned scale', 'rapid new construction', 'coastal Gulf exposure', 'within 50-mile Tampa service radius'],
    placeholder: true,
  },
  {
    slug: 'sarasota',
    name: 'Sarasota',
    county: 'Sarasota',
    zip: ['34231', '34232', '34233', '34234', '34235', '34236', '34237', '34238', '34239', '34240', '34241', '34242'],
    population: '56,000+',
    lat: 27.3364,
    lng: -82.5307,
    intro: 'Sarasota dryer vent cleaning extends the Airflow service footprint to the luxury waterfront market of Siesta Key, Longboat Key, and downtown Sarasota — approximately 55 miles from our Tampa base, available by appointment for quality-focused Sarasota-area clients.',
    why: 'Sarasota County has one of the highest concentrations of luxury waterfront homes and seasonal snowbird properties in Florida. Vacant winter months allow moisture and pest intrusion into vent systems; heavy seasonal use during resident months then compacts lint fast. Semiannual professional cleaning is the typical recommendation here.',
    neighborhoods: ['Siesta Key', 'Longboat Key', 'Downtown Sarasota', 'Palmer Ranch', 'Lakewood Ranch (south)'],
    landmarks: ['Siesta Key Beach', 'Ringling Museum', 'St. Armands Circle'],
    drivers: ['luxury waterfront housing', 'snowbird seasonal occupancy', 'Gulf-facing salt exposure', 'semiannual cleaning standard'],
    placeholder: true,
  },
];

export const getAreaBySlug = (slug: string) => areas.find((a) => a.slug === slug);
