export const posts = [
  {
    slug: 'how-often-dryer-vent-cleaning-tampa',
    title: 'How Often Should You Clean Your Dryer Vent in Tampa?',
    excerpt: 'Tampa\'s humidity and year-round dryer use mean annual cleaning is essential. Here\'s exactly when — and why — to schedule your next service.',
    date: '2026-04-10',
    readTime: '6 min',
    category: 'Maintenance',
  },
  {
    slug: 'dryer-vent-fire-warning-signs',
    title: '7 Warning Signs Your Dryer Vent Is a Fire Hazard',
    excerpt: 'Burning smells, long dry times, hot dryer surfaces — these warning signs mean your vent needs immediate professional attention.',
    date: '2026-04-02',
    readTime: '5 min',
    category: 'Safety',
  },
  {
    slug: 'dryer-vent-cleaning-cost-tampa-bay',
    title: 'How Much Does Dryer Vent Cleaning Cost in Tampa Bay?',
    excerpt: 'Complete 2026 pricing guide for residential, commercial, and multi-family dryer vent cleaning across Tampa, St. Pete, and Clearwater.',
    date: '2026-03-22',
    readTime: '8 min',
    category: 'Pricing',
  },
  {
    slug: 'flexible-foil-dryer-ducting-dangers',
    title: 'Why Flexible Foil Dryer Ducting Is a Hidden Fire Risk',
    excerpt: 'If your dryer vent uses plastic or foil ducting, you may be operating outside current safety code. Here\'s what to do.',
    date: '2026-03-15',
    readTime: '7 min',
    category: 'Safety',
  },
  {
    slug: 'dryer-vent-cleaning-vs-diy',
    title: 'Professional vs DIY Dryer Vent Cleaning: What Actually Works',
    excerpt: 'Brush kits from hardware stores seem convenient — but they miss up to 60% of lint buildup. Here\'s why professional cleaning matters.',
    date: '2026-03-08',
    readTime: '6 min',
    category: 'DIY',
  },
  {
    slug: 'commercial-dryer-vent-compliance-florida',
    title: 'Commercial Dryer Vent Compliance in Florida: What Property Managers Need to Know',
    excerpt: 'NFPA 211 documentation, insurance requirements, and scheduled maintenance — everything Florida property managers need for compliance.',
    date: '2026-02-28',
    readTime: '10 min',
    category: 'Commercial',
  },
];
